### ISSUE TITLE
Project Idea Feedback

### ISSUE THREAD

**Issue by bursteinalan** [CS521-Burstein/final-project-Pengchao_Wang#1]
-Deliverable not met

**Comment by YiYun0305** [comment]
Sorry professor, there is something wrong with my PyCharm. Git cannot run normally and update readme file, so it cannot be uploaded in time. I am still trying to repair it, and I have completed the project background. I'm trying to fix this tonight.

**Comment by YiYun0305** [comment]
I have fix it right now! You can check it. @bursteinalan

**Comment by bursteinalan** [comment]
The idea has a lot of potential, but you need to think through what you want to analyze more thoroughly.
It won't be enough to do something like 2-stock portfolio comparisons or calculating the return of a portfolio: this is just a for loop.
You will need to formulate a question like: "how does x affect y", something like: "how does the performance of AMC impact future option volume".

**Comment by YiYun0305** [comment]
Hi professor, I have revised my idea, you can review it again! @bursteinalan

**Comment by YiYun0305** [comment]
I have another question about data. I cannot use the CSV file I have downloaded. I have to write a program to download the S&P 500 data from the website? @bursteinalan

**Comment by bursteinalan** [comment]
As a single person group, you don't have to, but I recommend trying to use https://pypi.org/project/yfinance/ instead of downloading (could be an extension if done well).
As for your new idea, I think it has potential. You could do some analysis that talks about a strategy of buying "x days after some event" and just passive investing. But you need to do something robust, I want to see some machine learning or something of comparable difficulty. This idea lends itself well to a lot of visual exploration, but you need to stay away from excel: all of your analysis should be done in Python and the results should be thorough and again not just a comparison
